### ISSUE TITLE
Error trying to build pyxmlsec 0.3.1

### ISSUE THREAD

**Issue by lsnk** [dnet/pyxmlsec#6] opened 2017-09-21 03:51 UTC
Hello. I'm getting following error trying to build pyxmlsec 0.3.1.
OS: 4.12.13-1-ARCH
Python: 2.7.13
Openssl version: core/openssl 1.1.0.f-2

```
    In file included from xmlsecmod.h:23:0,
                     from x509.c:14:
    /usr/include/xmlsec1/xmlsec/x509.h:69:33: note: declared here
     XMLSEC_EXPORT int               xmlSecX509DataGetNodeContent    (xmlNodePtr node,
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    error: command 'gcc' failed with exit status 1

```

Any chance I can fix that? Tried building from sources and from our pypi server. Same result.

**Comment by dnet** [comment] 2017-09-21 08:24
Are you sure that it's the whole error message? It seems to be a second part of a longer message, as GCC usually says `note: declared here` when there's something wrong and it tries to help by appending these lines to the _actual root cause_ to help you find the bug.

**Comment by lsnk** [comment] 2017-09-21 08:26
I've fixed this exact error by downgrading xmlsec from 1.2.24-1 to 1.2.19-1.

**Comment by dnet** [comment] 2017-09-21 08:41
Thanks for the info, I'll close this for now. If you'll have additional info about what changed and how to make this work with newer versions, feel free to reopen and paste this here.

**Closed by dnet** 2017-09-21 08:41 UTC

**Comment by erny** [comment] 2019-06-04 09:28
Thanks.

With Ubuntu 18.04, I have now this exact error:

    x509.c:35:9: error: too many arguments to function ‘xmlSecX509DataGetNodeContent’
       ret = xmlSecX509DataGetNodeContent(node, deleteChildren, keyInfoCtx);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from xmlsecmod.h:23:0,
                     from x509.c:14:
    /usr/include/xmlsec1/xmlsec/x509.h:69:33: note: declared here
     XMLSEC_EXPORT int               xmlSecX509DataGetNodeContent    (xmlNodePtr node,
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

I'll try your fix, downgrading. On the the other hand, pyxmlsec and https://pypi.org/project/xmlsec/ clash. This happens if I want to use suds + sudssigner and zeep[xmlsec].

**Comment by erny** [comment] 2019-06-04 10:06
Link to issue in libxmlsec: https://github.com/lsh123/xmlsec/issues/266
